# Generated by Django 6.0.2 on 2026-02-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('institution', models.CharField(blank=True, max_length=200, verbose_name='Instituição')),
                ('year', models.CharField(blank=True, max_length=10, verbose_name='Ano')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='Arquivo (PDF ou imagem)')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
