# Generated by Django 6.0.2 on 2026-02-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_certification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certification',
            options={'ordering': ['section', 'order', '-year']},
        ),
        migrations.RemoveField(
            model_name='certification',
            name='certificate_file',
        ),
        migrations.AddField(
            model_name='certification',
            name='section',
            field=models.CharField(choices=[('formacao', 'Formação Profissional'), ('especializacoes', 'Especializações'), ('experiencia', 'Experiência Profissional'), ('eventos', 'Experiências em Evento')], default='formacao', max_length=30, verbose_name='Seção'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Ordem dentro da seção'),
        ),
    ]
