# Generated by Django 6.0.2 on 2026-02-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_certification_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certification',
            options={'ordering': ['section', 'order', '-year'], 'verbose_name': 'Certificação', 'verbose_name_plural': 'Certificações'},
        ),
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Imagem da Galeria', 'verbose_name_plural': 'Galeria de Imagens'},
        ),
        migrations.AddField(
            model_name='certification',
            name='certificate_image',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/', verbose_name='Imagem do certificado'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Ordem dentro da seção', verbose_name='Ordem'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=200, verbose_name='Texto alternativo'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(upload_to='gallery/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordem'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='title',
            field=models.CharField(blank=True, max_length=150, verbose_name='Título'),
        ),
    ]
