# Generated by Django 6.0.2 on 2026-02-18 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Destaque'),
        ),
    ]
