# Generated by Django 6.0.2 on 2026-02-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_service_is_featured'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['category', 'order', 'title'], 'verbose_name': 'Serviço', 'verbose_name_plural': 'Serviços'},
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('massagens', 'Massagens'), ('experiencias', 'Experiências')], default='massagens', max_length=20, verbose_name='Categoria'),
        ),
    ]
