# Generated by Django 6.0.2 on 2026-02-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_service_options_service_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('text', models.TextField(verbose_name='Depoimento')),
                ('role', models.CharField(blank=True, help_text='Ex: Cliente, Evento corporativo, etc.', max_length=120, verbose_name='Cargo / Contexto')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='Foto (opcional)')),
                ('highlight', models.BooleanField(default=False, verbose_name='Destaque')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Testemunho',
                'verbose_name_plural': 'Testemunhos',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='certification',
            name='year',
            field=models.CharField(blank=True, max_length=20, verbose_name='Ano'),
        ),
    ]
