# Generated by Django 6.0.2 on 2026-02-22 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_testimonial_alter_certification_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='highlight',
        ),
    ]
